hard_tabs = false
imports_layout = "Vertical"
max_width = 100
normalize_comments = true
struct_lit_single_line = false
tab_spaces = 4
trailing_comma = "Vertical"
indent_style = "Block"
trailing_semicolon = true
type_punctuation_density = "Wide"
brace_style = "SameLineWhere"
empty_item_single_line = true
control_brace_style = "AlwaysSameLine"
binop_separator = "Front"
fn_args_layout = "Tall"
imports_granularity = "Crate"
newline_style = "Unix"
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true

